# ã‚µã‚¤ãƒˆã®åŸºæœ¬æƒ…å ±
site_name: My Awesome Project Docs  # ã‚µã‚¤ãƒˆã‚¿ã‚¤ãƒˆãƒ«ï¼ˆãƒ–ãƒ©ã‚¦ã‚¶ã®ã‚¿ãƒ–ã‚„ãƒ˜ãƒƒãƒ€ãƒ¼ã«è¡¨ç¤ºï¼‰
site_url: https://example.com/     # ä»»æ„: ã‚µã‚¤ãƒˆã®å…¬é–‹URL

# Materialãƒ†ãƒ¼ãƒã®æœ‰åŠ¹åŒ–
theme:
    name: material
    
    # windmillã ã¨mermaidãŒè¡¨ç¤ºã•ã‚Œãªã„
    # name: windmill
    
    # è¨€èªã‚’æ—¥æœ¬èªã«è¨­å®šï¼ˆã‚µã‚¤ãƒˆå†…ã®æ—¥ä»˜ã‚„æ¤œç´¢ãªã©ã®UIãŒæ—¥æœ¬èªã«ãªã‚Šã¾ã™ï¼‰
    language: ja

# ãƒŠãƒ“ã‚²ãƒ¼ã‚·ãƒ§ãƒ³ï¼ˆç›®æ¬¡ï¼‰ã®å®šç¾©
nav:
    - ãƒ›ãƒ¼ãƒ : index.md             # docs/index.md ã«å¯¾å¿œ
    - ä½¿ã„æ–¹ã‚¬ã‚¤ãƒ‰:                 # ğŸ‘ˆ ãƒˆãƒƒãƒ—ãƒ¬ãƒ™ãƒ«ã®è¦‹å‡ºã— (è¦ª)
        - ã¯ã˜ã‚ã‚‹: sample_dir/test.md


markdown_extensions:

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search:
      lang: ja
