[project]
name = "how-to-marimo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "marimo>=0.19.4",
    "pandas>=2.3.3",
    "pyzmq>=27.1.0",
]
